import './globals.css';
import type { Metadata } from 'next';
import { Locale, i18n } from '@/i18n.config';
import Header from './components/Header';
import Footer from './components/Footer';
import { AlertProvider } from './context/alertContext';

//fonts
import { Karla, Markazi_Text } from 'next/font/google';
const karla = Karla({ subsets: ['latin'] });
const markazi = Markazi_Text({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: Locale };
}) {
	return (
		<html lang={params.lang}>
			<body className={karla.className}>
				<Header lang={params.lang} />
				<AlertProvider>
					<main>{children}</main>
				</AlertProvider>
				<Footer lang={params.lang} />
			</body>
		</html>
	);
}
